baseURL = "https://atecon.github.io/"
languageCode = "en-us"
title = "atecon's blog"
theme = "blackburn"
canonifyurls = true
paginate = 8
author = "Artur Tarassow"

#[indexes]
  #tag = "tags"
  #topic = "topics"


[params]
# Shown in the home page
  subtitle = "atecon's blog"
  brand = "atecon"
  # googleAnalytics = "Your Google Analytics tracking ID"
  description = "Economist, Data Scientist, Developer"
  avatar = "https://avatars2.githubusercontent.com/u/42611512?s=460&u=190e861586e4a701f33e755f51ec2b624d1788c1&v=4"


[social]
  github="atecon"
  twitter="atecon1"
  stackoverflow="https://stackoverflow.com/users/13028724/atecon"
  xing="Artur_Tarassow"


# sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 3
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research"
    #parent = "Research"
    weight = 4
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 5
