baseURL = "https://atecon.github.io/"
languageCode = "en-us"
title = "atecon's blog"
theme = "contrast-hugo"


[params]
  author = "Artur Tarassow"
  description = "Economist, Data Scientist, Developer"
  avatar = "https://avatars2.githubusercontent.com/u/42611512?s=460&u=190e861586e4a701f33e755f51ec2b624d1788c1&v=4"
  # mainSections = ["blog", "post"]
  favicon             = false
  svg                 = true
  faviconVersion      = "1"

  [[params.social]]
    name = "github"
    url = "https://github.com/atecon"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/atecon1"

  [[params.social]]
    name = "repec"
    url = "https://ideas.repec.org/f/pta322.html"

  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/13028724/atecon"

  [[params.social]]
    name = "linkedIn"
    url = ""


# sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 3
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research"
    #parent = "Research"
    weight = 4
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 5
